"""Initial baseline

Revision ID: aa820297bd1e
Revises: 
Create Date: 2026-02-21 08:02:04.048808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa820297bd1e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('assets_ticker_key'), 'assets', type_='unique')
    op.create_index(op.f('ix_assets_ticker'), 'assets', ['ticker'], unique=True)
    op.alter_column('daily_prices', 'asset_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_daily_prices_date'), 'daily_prices', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_prices_date'), table_name='daily_prices')
    op.alter_column('daily_prices', 'asset_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_assets_ticker'), table_name='assets')
    op.create_unique_constraint(op.f('assets_ticker_key'), 'assets', ['ticker'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
